from typing import Any

from .base import AIProvider


class DeterministicAIProvider(AIProvider):
    name = "deterministic"

    def generate_json(
        self,
        *,
        task: str,
        system_prompt: str,
        user_prompt: str,
        schema_hint: dict[str, Any] | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        return {
            "provider": self.name,
            "task": task,
            "content": user_prompt,
            "structured": {},
            "safety_note": (
                "Generated by deterministic local logic. "
                "Doctor review is required before clinical use."
            ),
            "metadata": metadata or {},
        }
